# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modelone.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 410)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button_export = QtWidgets.QPushButton(self.centralwidget)
        self.Button_export.setGeometry(QtCore.QRect(50, 230, 81, 21))
        self.Button_export.setObjectName("Button_export")
        self.vpn_password = QtWidgets.QPushButton(self.centralwidget)
        self.vpn_password.setGeometry(QtCore.QRect(160, 230, 121, 21))
        self.vpn_password.setObjectName("vpn_password")
        self.vpn_username_2 = QtWidgets.QLabel(self.centralwidget)
        self.vpn_username_2.setGeometry(QtCore.QRect(50, 50, 81, 21))
        self.vpn_username_2.setObjectName("vpn_username_2")
        self.label_vpnp = QtWidgets.QLabel(self.centralwidget)
        self.label_vpnp.setGeometry(QtCore.QRect(50, 98, 81, 21))
        self.label_vpnp.setObjectName("label_vpnp")
        self.vu = QtWidgets.QLineEdit(self.centralwidget)
        self.vu.setGeometry(QtCore.QRect(190, 50, 113, 20))
        self.vu.setObjectName("vu")
        self.vp = QtWidgets.QLineEdit(self.centralwidget)
        self.vp.setGeometry(QtCore.QRect(190, 100, 113, 20))
        self.vp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.vp.setObjectName("vp")
        self.iu = QtWidgets.QLineEdit(self.centralwidget)
        self.iu.setGeometry(QtCore.QRect(440, 50, 113, 20))
        self.iu.setObjectName("iu")
        self.ip = QtWidgets.QLineEdit(self.centralwidget)
        self.ip.setGeometry(QtCore.QRect(440, 100, 113, 20))
        self.ip.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ip.setObjectName("ip")
        self.label_inciteu = QtWidgets.QLabel(self.centralwidget)
        self.label_inciteu.setGeometry(QtCore.QRect(310, 50, 101, 20))
        self.label_inciteu.setObjectName("label_inciteu")
        self.label_incitep = QtWidgets.QLabel(self.centralwidget)
        self.label_incitep.setGeometry(QtCore.QRect(310, 100, 101, 21))
        self.label_incitep.setObjectName("label_incitep")
        self.label_years = QtWidgets.QLabel(self.centralwidget)
        self.label_years.setGeometry(QtCore.QRect(50, 150, 141, 16))
        self.label_years.setObjectName("label_years")
        self.label_yeare = QtWidgets.QLabel(self.centralwidget)
        self.label_yeare.setGeometry(QtCore.QRect(310, 150, 131, 20))
        self.label_yeare.setObjectName("label_yeare")
        self.Button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Button_3.setGeometry(QtCore.QRect(310, 230, 81, 20))
        self.Button_3.setObjectName("Button_3")
        self.graph1 = QtWidgets.QPushButton(self.centralwidget)
        self.graph1.setGeometry(QtCore.QRect(430, 230, 56, 21))
        self.graph1.setObjectName("graph1")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 261, 701, 131))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        self.textBrowser.setFont(font)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser.setObjectName("textBrowser")
        self.graph2 = QtWidgets.QPushButton(self.centralwidget)
        self.graph2.setGeometry(QtCore.QRect(530, 230, 56, 21))
        self.graph2.setObjectName("graph2")
        self.ystart = QtWidgets.QLineEdit(self.centralwidget)
        self.ystart.setGeometry(QtCore.QRect(190, 150, 111, 20))
        self.ystart.setObjectName("ystart")
        self.yend = QtWidgets.QLineEdit(self.centralwidget)
        self.yend.setGeometry(QtCore.QRect(440, 150, 111, 20))
        self.yend.setObjectName("yend")
        self.ddl = QtWidgets.QLineEdit(self.centralwidget)
        self.ddl.setGeometry(QtCore.QRect(190, 190, 113, 20))
        self.ddl.setObjectName("ddl")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 190, 161, 21))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.Button_export.clicked.connect(MainWindow.export_test)
        self.graph1.clicked.connect(MainWindow.graph_polyline)
        self.graph2.clicked.connect(MainWindow.graph_columnar)
        self.vpn_password.clicked.connect(MainWindow.frequency_test)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_export.setText(_translate("MainWindow", "导出初始表"))
        self.vpn_password.setText(_translate("MainWindow", "计算被引频次"))
        self.vpn_username_2.setText(_translate("MainWindow", "vpn_username"))
        self.label_vpnp.setText(_translate("MainWindow", "vpn_password"))
        self.label_inciteu.setText(_translate("MainWindow", "incite_username"))
        self.label_incitep.setText(_translate("MainWindow", "incite_password"))
        self.label_years.setText(_translate("MainWindow", "year_start(eg.1999)"))
        self.label_yeare.setText(_translate("MainWindow", "year_end(eg.2009)"))
        self.Button_3.setText(_translate("MainWindow", "计算接近度"))
        self.graph1.setText(_translate("MainWindow", "Graph1"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p></body></html>"))
        self.graph2.setText(_translate("MainWindow", "Graph2"))
        self.label.setText(_translate("MainWindow", "截止日期（eg.20200430）"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
