# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modeltwo.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(848, 383)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Desktop/华电.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 834, 325))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.yend = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.yend.setObjectName("yend")
        self.gridLayout.addWidget(self.yend, 2, 6, 1, 3)
        self.radioButton_3 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 6, 3, 1, 1)
        self.vpn_password = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.vpn_password.setObjectName("vpn_password")
        self.gridLayout.addWidget(self.vpn_password, 9, 2, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 5, 4, 1, 3)
        self.iu = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.iu.setObjectName("iu")
        self.gridLayout.addWidget(self.iu, 0, 6, 1, 3)
        self.label_yeare = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_yeare.setObjectName("label_yeare")
        self.gridLayout.addWidget(self.label_yeare, 2, 3, 1, 3)
        self.Button_export = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Button_export.setObjectName("Button_export")
        self.gridLayout.addWidget(self.Button_export, 9, 0, 1, 2)
        self.textBrowser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(7)
        self.textBrowser.setFont(font)
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 10, 0, 1, 9)
        self.vu = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.vu.setObjectName("vu")
        self.gridLayout.addWidget(self.vu, 0, 2, 1, 1)
        self.vpn_username = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.vpn_username.setObjectName("vpn_username")
        self.gridLayout.addWidget(self.vpn_username, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 2)
        self.radioButton = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 5, 3, 1, 1)
        self.vp = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.vp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.vp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.vp.setObjectName("vp")
        self.gridLayout.addWidget(self.vp, 1, 2, 1, 1)
        self.ystart = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ystart.setObjectName("ystart")
        self.gridLayout.addWidget(self.ystart, 2, 2, 1, 1)
        self.label_incitep = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_incitep.setObjectName("label_incitep")
        self.gridLayout.addWidget(self.label_incitep, 1, 3, 1, 2)
        self.label_inciteu = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_inciteu.setObjectName("label_inciteu")
        self.gridLayout.addWidget(self.label_inciteu, 0, 3, 1, 2)
        self.ip = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ip.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ip.setObjectName("ip")
        self.gridLayout.addWidget(self.ip, 1, 6, 1, 3)
        self.label_years = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_years.setObjectName("label_years")
        self.gridLayout.addWidget(self.label_years, 2, 0, 1, 2)
        self.label_vpnp = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_vpnp.setObjectName("label_vpnp")
        self.gridLayout.addWidget(self.label_vpnp, 1, 0, 1, 1)
        self.ddl = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ddl.setObjectName("ddl")
        self.gridLayout.addWidget(self.ddl, 5, 2, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout.addWidget(self.radioButton_4, 6, 4, 1, 1)
        self.Button_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Button_3.setObjectName("Button_3")
        self.gridLayout.addWidget(self.Button_3, 9, 3, 1, 1)
        self.graph1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.graph1.setObjectName("graph1")
        self.gridLayout.addWidget(self.graph1, 9, 4, 1, 1)
        self.graph2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.graph2.setObjectName("graph2")
        self.gridLayout.addWidget(self.graph2, 9, 6, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 848, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.vpn_password.clicked.connect(MainWindow.frequency_test)
        self.graph1.clicked.connect(MainWindow.graph_columnar)
        self.graph2.clicked.connect(MainWindow.graph_polyline)
        self.Button_export.clicked.connect(MainWindow.export_test)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "华北电力大学CS学科ESI查询系统"))
        self.radioButton_3.setText(_translate("MainWindow", "线程3"))
        self.vpn_password.setText(_translate("MainWindow", "计算被引频次"))
        self.radioButton_2.setText(_translate("MainWindow", "线程2"))
        self.label_yeare.setText(_translate("MainWindow", "year_end(eg.2009)"))
        self.Button_export.setText(_translate("MainWindow", "导出初始表"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p></body></html>"))
        self.vpn_username.setText(_translate("MainWindow", "vpn_username"))
        self.label.setText(_translate("MainWindow", "截止日期（eg.20200430）"))
        self.radioButton.setText(_translate("MainWindow", "线程1"))
        self.label_incitep.setText(_translate("MainWindow", "incite_password"))
        self.label_inciteu.setText(_translate("MainWindow", "incite_username"))
        self.label_years.setText(_translate("MainWindow", "year_start(eg.1999)"))
        self.label_vpnp.setText(_translate("MainWindow", "vpn_password"))
        self.radioButton_4.setText(_translate("MainWindow", "线程4"))
        self.Button_3.setText(_translate("MainWindow", "计算接近度"))
        self.graph1.setText(_translate("MainWindow", "折线图"))
        self.graph2.setText(_translate("MainWindow", "对比图"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
